# -*- coding: utf-8 -*-
"""
SolidWorks sheet-metal PDF builder.

Creates one PDF per unique sheet-metal part/configuration and puts the PDFs
into folders grouped by thickness:

    <output>/
        1.5mm/
            Part-A.pdf
            Part-B.pdf
        2mm/
            Part-C.pdf

The PDF is generated by SOLIDWORKS itself, not by converting the existing DXF.
That allows the drawing to contain a real flat-pattern drawing view, model
dimensions (when the part has dimensions marked for drawings), and a native
SOLIDWORKS bend table.

For the closest match to the supplied sample, set drawing_template to a
custom .drwdot that contains the desired A4 title block. If drawing_template
is None, the user's SOLIDWORKS default drawing template is used.
"""

import gc
import os
import re
import time
from pathlib import Path

import pythoncom
from win32com.client import VARIANT


SW_DOC_PART = 1
SW_DOC_DRAWING = 3
SW_OPEN_SILENT = 1

# swUserPreferenceStringValue_e.swDefaultTemplateDrawing
SW_DEFAULT_TEMPLATE_DRAWING = 10

# swInsertAnnotation_e
SW_INSERT_DIMENSIONS_MARKED_FOR_DRAWING = 32768

# swImportModelItemsSource_e
SW_IMPORT_MODEL_ITEMS_FROM_ENTIRE_MODEL = 0

# swExportData_ExportSpecifiedSheets
SW_EXPORT_SPECIFIED_SHEETS = 0

# GetExportFileData(swExportDataFileType_e.swExportPdfData)
# In the SolidWorks API examples this is 1.
SW_EXPORT_PDF_DATA = 1

INVALID_FILENAME = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


class SolidWorksPdfBuilder:
    """
    Create one SolidWorks drawing/PDF for every sheet-metal item.

    The input records are the same records produced by SheetMetalDetector:
        name, path, configuration, quantity, mirror_quantity,
        thickness, mirror_parts, ...

    The exporter argument is the existing DwgExporter instance. Reusing it
    means part opening/reconnect/rebuild behavior stays consistent with the
    current application.
    """

    def __init__(
        self,
        sw_app,
        exporter=None,
        drawing_template=None,
        bend_table_template=None,
        keep_drawings=False,
        view_x=0.145,
        view_y=0.115,
        max_view_width=0.175,
        max_view_height=0.095,
        min_view_scale=0.05,
        add_dimensions=True,
        add_bend_table=True,
        add_qty_note=True,
    ):
        self.sw_app = sw_app
        self.exporter = exporter
        self.drawing_template = (
            Path(drawing_template).resolve() if drawing_template else None
        )
        self.bend_table_template = (
            Path(bend_table_template).resolve() if bend_table_template else None
        )
        self.keep_drawings = keep_drawings

        # Coordinates are drawing-sheet coordinates in meters.
        self.view_x = float(view_x)
        self.view_y = float(view_y)
        self.max_view_width = float(max_view_width)
        self.max_view_height = float(max_view_height)
        self.min_view_scale = float(min_view_scale)

        self.add_dimensions = bool(add_dimensions)
        self.add_bend_table = bool(add_bend_table)
        self.add_qty_note = bool(add_qty_note)

    # ------------------------------------------------------------------
    # Generic helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _safe_filename(name):
        cleaned = INVALID_FILENAME.sub("_", str(name)).strip().rstrip(".")
        return re.sub(r"\s+", " ", cleaned) or "part"

    @staticmethod
    def _written(path):
        try:
            p = Path(path)
            return p.exists() and p.stat().st_size > 0
        except Exception:
            return False

    @staticmethod
    def _get(obj, name, default=None):
        if obj is None:
            return default
        try:
            value = getattr(obj, name)
            return value() if callable(value) else value
        except Exception:
            return default

    @staticmethod
    def _call(obj, name, *args, default=None):
        if obj is None:
            return default
        try:
            method = getattr(obj, name)
            return method(*args) if callable(method) else default
        except Exception:
            return default

    @staticmethod
    def _byref_i4():
        return VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)

    # ------------------------------------------------------------------
    # Templates
    # ------------------------------------------------------------------

    def _get_drawing_template(self):
        if self.drawing_template:
            if not self.drawing_template.exists():
                raise FileNotFoundError(
                    f"Drawing template not found: {self.drawing_template}"
                )
            return str(self.drawing_template)

        # Some SolidWorks/PyWin32 COM versions do not expose
        # GetUserPreferenceStringValue through the late-bound COM object.
        # GetDocumentTemplate is a safer API for obtaining the active drawing
        # template. 6 = swDwgPaperA4size, matching the requested sample.
        try:
            template = self.sw_app.GetDocumentTemplate(
                SW_DOC_DRAWING,
                "",
                6,
                0.0,
                0.0,
            )
            if template and Path(str(template)).exists():
                return str(template)
        except Exception:
            pass

        # Final fallback: let NewDocument try SolidWorks' configured default.
        return ""

    def _find_bend_table_template(self):
        if self.bend_table_template:
            if self.bend_table_template.exists():
                return str(self.bend_table_template)
            raise FileNotFoundError(
                f"Bend-table template not found: {self.bend_table_template}"
            )

        # Common SolidWorks installation locations.
        roots = []
        for env_name in ("ProgramFiles", "ProgramFiles(x86)"):
            root = os.environ.get(env_name)
            if root:
                roots.append(Path(root))

        candidates = []
        for root in roots:
            for lang in ("english", "English"):
                candidates.extend(
                    [
                        root
                        / "SOLIDWORKS Corp"
                        / "SOLIDWORKS"
                        / "lang"
                        / lang
                        / "bendtable-standard.sldbndtbt",
                        root
                        / "SOLIDWORKS Corp"
                        / "SOLIDWORKS"
                        / "lang"
                        / lang
                        / "bendtable-standard.sldbndtbt",
                    ]
                )

        for candidate in candidates:
            if candidate.exists():
                return str(candidate)

        # Last resort: bounded search below Program Files.
        for root in roots:
            try:
                matches = list(
                    root.glob(
                        "SOLIDWORKS Corp/SOLIDWORKS/lang/*/bendtable-standard.sldbndtbt"
                    )
                )
                if matches:
                    return str(matches[-1])
            except Exception:
                pass

        return None

    # ------------------------------------------------------------------
    # Part open/config/rebuild
    # ------------------------------------------------------------------

    def _open_part(self, path):
        if self.exporter is not None:
            return self.exporter._open_part(path)

        path = Path(path).resolve()

        try:
            existing = self.sw_app.GetOpenDocumentByName(str(path))
            if existing is not None:
                return existing, False, "already open"
        except Exception:
            pass

        errors = self._byref_i4()
        warnings = self._byref_i4()

        model = self.sw_app.OpenDoc6(
            str(path), SW_DOC_PART, SW_OPEN_SILENT, "", errors, warnings
        )
        if model is None:
            return None, False, "OpenDoc6 returned None"

        return model, True, "opened"

    def _close_part(self, model, opened_by_us):
        if model is None or not opened_by_us:
            return

        title = self._get(model, "GetTitle")
        try:
            if title:
                self.sw_app.CloseDoc(str(title))
        except Exception:
            pass

        del model
        gc.collect()

    def _activate_configuration(self, model, configuration):
        if self.exporter is not None:
            return self.exporter._activate_configuration(model, configuration)

        if not configuration:
            return True, None

        manager = self._call(model, "ConfigurationManager")
        active = self._call(manager, "ActiveConfiguration")
        previous = self._get(active, "Name")

        try:
            return bool(model.ShowConfiguration2(str(configuration))), previous
        except Exception:
            return False, previous

    def _restore_configuration(self, model, previous):
        if previous:
            try:
                model.ShowConfiguration2(str(previous))
            except Exception:
                pass

    def _rebuild(self, model):
        if self.exporter is not None:
            return self.exporter._rebuild(model)

        try:
            return bool(model.ForceRebuild3(True)), "ForceRebuild3"
        except Exception as exc:
            try:
                return bool(model.EditRebuild3()), "EditRebuild3"
            except Exception as exc2:
                return False, f"{exc}; {exc2}"

    # ------------------------------------------------------------------
    # Drawing creation
    # ------------------------------------------------------------------

    def _new_drawing(self):
        template = self._get_drawing_template()

        drawing = self.sw_app.NewDocument(template, 0, 0, 0)
        if drawing is None:
            raise RuntimeError(
                f"SolidWorks could not create drawing from template: {template}"
            )

        return drawing

    @staticmethod
    def _get_first_model_view(drawing):
        """
        Skip the sheet-format view. Return the first actual drawing view.
        """
        view = drawing.GetFirstView()
        if view is not None:
            view = view.GetNextView()

        return view

    def _create_flat_pattern_view(self, drawing, item):
        part_path = str(Path(item["path"]).resolve())
        config = str(item.get("configuration") or "")

        # A4 landscape sheet uses meter coordinates.
        view = drawing.CreateFlatPatternViewFromModelView3(
            part_path,
            config,
            self.view_x,
            self.view_y,
            0.0,
            False,  # keep bend lines visible
            False,  # do not flip
        )

        if view is None:
            raise RuntimeError(
                f"CreateFlatPatternViewFromModelView3 failed for {item['name']}"
            )

        # Keep bend notes available when the SolidWorks version supports it.
        try:
            view.ShowSheetMetalBendNotes = True
        except Exception:
            pass

        return view

    def _fit_view(self, drawing, view):
        """
        Fit the flat pattern into the upper/central A4 area.

        The exact visual result is intentionally left to the drawing template;
        this only scales and places the model view so large/small parts remain
        printable.
        """
        try:
            outline = view.GetOutline()
            if outline is None or len(outline) < 4:
                return

            x_min, y_min, x_max, y_max = map(float, outline[:4])
            width = abs(x_max - x_min)
            height = abs(y_max - y_min)

            if width <= 0 or height <= 0:
                return

            scale_x = self.max_view_width / width
            scale_y = self.max_view_height / height
            scale = min(scale_x, scale_y)

            # Do not enlarge tiny parts excessively.
            scale = min(scale, 1.0)
            scale = max(scale, self.min_view_scale)

            view.UseSheetScale = 0
            view.ScaleDecimal = scale
            view.Position = (self.view_x, self.view_y)

            try:
                drawing.ForceRebuild3(True)
            except Exception:
                pass
        except Exception:
            # A failed auto-fit should not prevent PDF creation.
            pass

    # ------------------------------------------------------------------
    # Dimensions
    # ------------------------------------------------------------------

    def _insert_model_dimensions(self, drawing, view):
        if not self.add_dimensions:
            return False

        try:
            drawing.ActivateView(view.GetName2())
        except Exception:
            pass

        try:
            drawing.ClearSelection2(True)
        except Exception:
            pass

        # Select and activate the view, following the SolidWorks API example.
        selected = False
        try:
            selected = bool(
                drawing.Extension.SelectByID2(
                    view.GetName2(),
                    "DRAWINGVIEW",
                    0,
                    0,
                    0,
                    False,
                    0,
                    None,
                    0,
                )
            )
        except Exception:
            pass

        try:
            drawing.ActivateView(view.GetName2())
        except Exception:
            pass

        try:
            result = drawing.InsertModelAnnotations3(
                SW_IMPORT_MODEL_ITEMS_FROM_ENTIRE_MODEL,
                SW_INSERT_DIMENSIONS_MARKED_FOR_DRAWING,
                False,
                True,
                False,
                True,
            )
            return result is not None
        except Exception:
            # Some parts have no dimensions marked for drawing. This is not
            # considered a fatal PDF error.
            return False
        finally:
            try:
                drawing.ClearSelection2(True)
            except Exception:
                pass

    # ------------------------------------------------------------------
    # Bend table
    # ------------------------------------------------------------------

    def _insert_bend_table(self, view):
        if not self.add_bend_table:
            return False, "disabled"

        template = self._find_bend_table_template()
        if not template:
            return False, "bend table template not found"

        try:
            # Position is sheet coordinates in meters. Use a free-standing
            # position so the user's template can reserve the title-block area.
            table = view.InsertBendTable(
                False,
                0.205,
                0.105,
                0,
                "A",
                template,
            )
            if table is None:
                return False, "InsertBendTable returned None"
            return True, "OK"
        except Exception as exc:
            return False, str(exc)

    # ------------------------------------------------------------------
    # Quantity / metadata
    # ------------------------------------------------------------------

    @staticmethod
    def _qty_text(item):
        quantity = int(item.get("quantity", 1) or 1)
        mirror = int(item.get("mirror_quantity", 0) or 0)
        own = quantity - mirror

        if mirror:
            return f"QTY={quantity}   ({own} + {mirror} MIRROR)"
        return f"QTY={quantity}"

    def _insert_note(self, drawing, text, x, y):
        try:
            note = drawing.InsertNote(text)
            if note is None:
                return False

            annotation = note.GetAnnotation()
            if annotation is not None:
                try:
                    annotation.SetPosition2(float(x), float(y), 0.0)
                except Exception:
                    try:
                        annotation.SetPosition(float(x), float(y), 0.0)
                    except Exception:
                        pass

            try:
                note.LockPosition = False
            except Exception:
                pass

            return True
        except Exception:
            return False

    def _insert_qty_note(self, drawing, item):
        if not self.add_qty_note:
            return False

        # Lower-left of the main drawing area; title block remains available
        # in the drawing template.
        return self._insert_note(
            drawing,
            self._qty_text(item),
            0.035,
            0.035,
        )

    def _set_drawing_custom_properties(self, drawing, item):
        """
        If the drawing template uses $PRP-linked title-block fields, these
        properties can populate them without hard-coding title-block geometry.
        """
        props = {
            "PART": str(item.get("name", "")),
            "PART NUMBER": str(item.get("name", "")),
            "DESCRIPTION": str(item.get("name", "")),
            "QTY": str(item.get("quantity", "")),
            "THICKNESS": (
                f"{item['thickness']:g} mm" if item.get("thickness") is not None else ""
            ),
            "MATERIAL": str(item.get("material", "")),
            "CONFIGURATION": str(item.get("configuration") or ""),
        }

        try:
            manager = drawing.Extension.CustomPropertyManager("")
            for name, value in props.items():
                try:
                    # Set2 exists in modern SolidWorks. If a version uses Add3
                    # instead, the title block still works from the template.
                    manager.Set2(name, value)
                except Exception:
                    try:
                        manager.Add3(name, 30, value, 2)
                    except Exception:
                        pass
        except Exception:
            pass

    # ------------------------------------------------------------------
    # PDF export
    # ------------------------------------------------------------------

    def _export_pdf(self, drawing, pdf_path):
        pdf_path = Path(pdf_path)
        pdf_path.parent.mkdir(parents=True, exist_ok=True)

        export_data = self.sw_app.GetExportFileData(SW_EXPORT_PDF_DATA)
        if export_data is None:
            raise RuntimeError("SolidWorks GetExportFileData(PDF) returned None")

        try:
            export_data.ViewPdfAfterSaving = False
        except Exception:
            pass

        sheet_names = drawing.GetSheetNames()
        if not sheet_names:
            raise RuntimeError("Drawing has no sheets")

        # One sheet per PDF.
        sheet_name = sheet_names[0]
        if not export_data.SetSheets(SW_EXPORT_SPECIFIED_SHEETS, sheet_name):
            raise RuntimeError("SetSheets failed for PDF export")

        errors = self._byref_i4()
        warnings = self._byref_i4()

        ok = drawing.Extension.SaveAs(
            str(pdf_path),
            0,
            0,
            export_data,
            errors,
            warnings,
        )

        if not ok or not self._written(pdf_path):
            raise RuntimeError(
                "PDF export failed "
                f"(errors={getattr(errors, 'value', errors)}, "
                f"warnings={getattr(warnings, 'value', warnings)})"
            )

        return True

    # ------------------------------------------------------------------
    # One part
    # ------------------------------------------------------------------

    def export_part_pdf(self, item, pdf_path):
        """
        Export one sheet-metal item to one PDF.

        Returns:
            (True, message) on success
            (False, error_message) on failure
        """
        pdf_path = Path(pdf_path)
        pdf_path.parent.mkdir(parents=True, exist_ok=True)

        if pdf_path.exists():
            try:
                pdf_path.unlink()
            except Exception as exc:
                return False, f"cannot remove old PDF: {exc}"

        model = None
        opened_by_us = False
        drawing = None
        previous_config = None

        try:
            model, opened_by_us, open_status = self._open_part(item["path"])
            if model is None:
                return False, open_status

            config_ok, previous_config = self._activate_configuration(
                model, item.get("configuration")
            )
            if item.get("configuration") and not config_ok:
                print(
                    f"  Warning: could not activate configuration "
                    f"{item['configuration']} for {item['name']}"
                )

            rebuilt, rebuild_message = self._rebuild(model)
            if not rebuilt:
                print(
                    f"  Warning: rebuild failed for {item['name']}: {rebuild_message}"
                )

            # Create the drawing while the referenced part is still open.
            drawing = self._new_drawing()

            self._set_drawing_custom_properties(drawing, item)

            view = self._create_flat_pattern_view(drawing, item)
            self._fit_view(drawing, view)

            dimensions_ok = self._insert_model_dimensions(drawing, view)
            bend_ok, bend_message = self._insert_bend_table(view)
            qty_ok = self._insert_qty_note(drawing, item)

            try:
                drawing.ForceRebuild3(True)
            except Exception:
                pass

            self._export_pdf(drawing, pdf_path)

            info = [
                "PDF OK",
                f"dims={'yes' if dimensions_ok else 'none'}",
                f"bend_table={'yes' if bend_ok else bend_message}",
                f"qty_note={'yes' if qty_ok else 'no'}",
            ]

            return True, "; ".join(info)

        except Exception as exc:
            return False, f"{type(exc).__name__}: {exc}"

        finally:
            # Close drawing first so its model reference is released.
            if drawing is not None:
                try:
                    title = self._get(drawing, "GetTitle")
                    if title:
                        self.sw_app.CloseDoc(str(title))
                except Exception:
                    pass

                del drawing
                gc.collect()

            if model is not None:
                self._restore_configuration(model, previous_config)
                self._close_part(model, opened_by_us)

            try:
                pythoncom.CoFreeUnusedLibraries()
            except Exception:
                pass

    # ------------------------------------------------------------------
    # Batch export grouped by thickness
    # ------------------------------------------------------------------

    def build(self, sheet_metal_parts, output_folder):
        output_folder = Path(output_folder)
        output_folder.mkdir(parents=True, exist_ok=True)

        parts = sorted(
            [p for p in sheet_metal_parts if p.get("thickness") is not None],
            key=lambda p: (float(p["thickness"]), str(p["name"]).lower()),
        )

        results = []
        failed = []
        used_names = set()

        print()
        print("=" * 60)
        print("PDF EXPORT: ONE DRAWING PER SHEET-METAL PART")
        print("=" * 60)

        for index, item in enumerate(parts, start=1):
            thickness = float(item["thickness"])
            thickness_folder = output_folder / f"{thickness:g}mm"
            thickness_folder.mkdir(parents=True, exist_ok=True)

            base = self._safe_filename(item["name"])
            unique = base
            counter = 2
            key = str(thickness) + "|" + unique.lower()

            while key in used_names or (thickness_folder / f"{unique}.pdf").exists():
                unique = f"{base}_{counter}"
                counter += 1
                key = str(thickness) + "|" + unique.lower()

            used_names.add(key)

            pdf_path = thickness_folder / f"{unique}.pdf"

            print(
                f"[{index}/{len(parts)}] "
                f"{item['name']} | {thickness:g} mm | "
                f"x{item.get('quantity', 1)}"
            )

            ok, message = self.export_part_pdf(item, pdf_path)

            if ok:
                print(f"    -> {pdf_path}")
                print(f"       {message}")
                results.append(
                    {
                        "name": item["name"],
                        "thickness": thickness,
                        "quantity": int(item.get("quantity", 1)),
                        "path": pdf_path,
                    }
                )
            else:
                print(f"    -> FAILED: {message}")
                failed.append((item["name"], message))

        print()
        print("=" * 60)
        print("PDF SUMMARY")
        print("=" * 60)
        print(f"PDFs created: {len(results)}")
        print(f"Failures:     {len(failed)}")

        for row in results:
            print(
                f"  {row['thickness']:g} mm | x{row['quantity']} | {row['path'].name}"
            )

        if failed:
            print()
            print("Failed PDF parts:")
            for name, message in failed:
                print(f"  - {name}: {message}")

        return {
            "files": results,
            "failed_parts": failed,
            "error": None,
        }
